project_id = "betvwipgtcrhmludzgxw"

[functions.auth-signup]
verify_jwt = false

[functions.fetch-from-siret]
verify_jwt = false

[functions.create-demo]
verify_jwt = true

[functions.import-csv-check]
verify_jwt = true

[functions.cleanup-login-logs]
verify_jwt = false

[functions.csp-report]
verify_jwt = false

[functions.create-simulator-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-contact]
verify_jwt = false

[functions.log-login]
verify_jwt = true

[functions.trial-reminder]
verify_jwt = false

[functions.create-subscription-checkout]
verify_jwt = true
