export const COMPARISON_STRINGS = {
  projectTitle: "Comparer 2 projets",
  scenarioTitle: "Comparer 2 scénarios",
  download: "Télécharger le comparatif",
  advantage: "Avantage",
  loss: "Perte",
  breakEvenShare: "{value} % du seuil",
  deltaTitle: "Différentiel – {a} vs {b}",
  delta: {
    result: "Résultat",
    revenue: "CA",
    costs: "Charges",
    breakEven: "Seuil",
  },
  radarTitle: "Profil comparé (6 axes)",
  roiTitle: "Trajectoire ROI (24 mois)",
  roiReference: "Référence",
  roiAxisMonth: "Mois",
  roiAxisAmount: "€",
  roiThreshold: "Seuil",
  synthesisTitle: "Synthèse automatique",
  fullAnalysis: "Voir l'analyse complète",
  footerHint: "Un scénario actif par projet · Recalcul instantané",
  pickTwo: "Sélectionnez deux éléments à comparer",
  radarAxes: {
    revenue: "CA",
    margin: "Marge",
    costs: "Charges",
    breakEven: "Seuil",
    roi: "ROI",
    volume: "Volume",
  },
} as const;
