// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/ping.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var ping_default = defineTool({
  name: "ping",
  title: "Ping",
  description: "Verify connectivity to the Lavcom Performances MCP server. Returns a pong with an optional echoed message and the server timestamp.",
  inputSchema: {
    message: z.string().max(200).optional().describe("Optional message echoed back in the response.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ message }) => ({
    content: [
      {
        type: "text",
        text: `pong${message ? ` \u2014 ${message}` : ""} (server time: ${(/* @__PURE__ */ new Date()).toISOString()})`
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lavcom-performances-mcp",
  title: "Lavcom Performances MCP",
  version: "0.1.0",
  instructions: "MCP server for Lavcom Performances (analytics SaaS for self-service laundromats). Use `ping` to verify connectivity. Additional authenticated tools for querying operations, revenue KPIs and simulations will be added in a follow-up.",
  tools: [ping_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
